server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 30m
      cookie:
        max-age: 1800
        http-only: true
        secure: true # 生产环境启用HTTPS

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your-production-host:3306/demo_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: ${DB_USERNAME:demo_user}
    password: ${DB_PASSWORD:demo_password}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:your-redis-host}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:your-redis-password}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 2

  session:
    store-type: redis
    timeout: 1800s
    redis:
      flush-mode: on-save
      namespace: spring:session:prod

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl # 生产环境关闭SQL日志
  global-config:
    db-config:
      logic-delete-field: deletedTime
      logic-delete-value: now()
      logic-not-delete-value: null
    banner: false

knife4j:
  enable: false # 生产环境关闭API文档
  production: true

# 应用自定义配置
app:
  name: SpringBoot通用后台服务
  version: 1.0.0
  description: 基于SpringBoot3的通用后台服务（生产环境）
  author: spark 